show_downloads: true
theme: jekyll-theme-slate

github:
  zip_url: https://github.com/shengyu7697/ScreenCapture/releases/download/v1.1.0/ScreenCapture-1.1.0-win32.7z
  another_url: https://github.com/shengyu7697/ScreenCapture/releases/download/v1.1.0/ScreenCapture-1.1.0-win64.7z
